export const TOP_EVENTS_START = "TOP_EVENTS_START"
export const TOP_EVENTS_SUCCESS = "TOP_EVENTS_SUCCESS"
export const TOP_EVENTS_ERROR = "TOP_EVENTS_ERROR"

export const SPORT_EVENTS_START = "SPORT_EVENTS_START"
export const SPORT_EVENTS_SUCCESS = "SPORT_EVENTS_SUCCESS"
export const SPORT_EVENTS_ERROR = "SPORT_EVENTS_ERROR"
export const SPORT_EVENTS_TYPE = "SPORT_EVENTS_TYPE"

export const SPORT_LOCATION_EVENTS_START = "SPORT_LOCATION_EVENTS_START"
export const SPORT_LOCATION_EVENTS_SUCCESS = "SPORT_LOCATION_EVENTS_SUCCESS"
export const SPORT_LOCATION_EVENTS_ERROR = "SPORT_LOCATION_EVENTS_ERROR"
export const SPORT_LOCATION_EVENTS_TYPE = "SPORT_LOCATION_EVENTS_TYPE"
