export const standingTable =  [
    {
        team: 'FC Minsk',        
        total: {
            q:1,
            p:2,
            w:2,
            d:0,
            l:0,
            goals:'6:3',
            last5:'w,w,l',
            pts:6
        },
        home:{
            q:3,
            p:1,
            w:1,
            d:0,
            l:0,
            goals:'3:1',
            last5:'w,w,l',
            pts:3
        },
        away:{
            q:3,
            p:1,
            w:1,
            d:0,
            l:0,
            goals:'3:1',
            last5:'w,w',
            pts:3
        }        
    },
    {
        team: 'Shakhtyor Soligorsk',
        total: {
            q:2,
            p:2,
            w:2,
            d:0,
            l:0,
            goals:'4:1',
            last5:'w,w,w,l,l',
            pts:6
        },
        home:{
            q:2,
            p:1,
            w:1,
            d:0,
            l:0,
            goals:'2:0',
            last5:'w,d',
            pts:3
        },
        away:{
            q:2,
            p:1,
            w:1,
            d:0,
            l:0,
            goals:'2:0',
            last5:'w,d',
            pts:3
        }        
    },    
    {
        team: 'Isloch',
        total: {
            q:3,
            p:2,
            w:2,
            d:0,
            l:0,
            goals:'2:0',
            last5:'w,w',
            pts:6
        },
        home:{
            q:1,
            p:2,
            w:1,
            d:0,
            l:1,
            goals:'3:2',
            last5:'w,l',
            pts:3
        },
        away:{
            q:1,
            p:1,
            w:1,
            d:0,
            l:0,
            goals:'1:0',
            last5:'w',
            pts:3
        }        
    },
]
